/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuccessSlugRouteImport } from './routes/success.$slug'
import { Route as ShortsSlugRouteImport } from './routes/shorts.$slug'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminImportRouteImport } from './routes/admin/import'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SuccessSlugRoute = SuccessSlugRouteImport.update({
  id: '/success/$slug',
  path: '/success/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsSlugRoute = ShortsSlugRouteImport.update({
  id: '/shorts/$slug',
  path: '/shorts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/import': typeof AdminImportRoute
  '/category/$slug': typeof CategorySlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/shorts/$slug': typeof ShortsSlugRoute
  '/success/$slug': typeof SuccessSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/import': typeof AdminImportRoute
  '/category/$slug': typeof CategorySlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/shorts/$slug': typeof ShortsSlugRoute
  '/success/$slug': typeof SuccessSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/import': typeof AdminImportRoute
  '/category/$slug': typeof CategorySlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/shorts/$slug': typeof ShortsSlugRoute
  '/success/$slug': typeof SuccessSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$slug'
    | '/login'
    | '/thank-you'
    | '/admin/import'
    | '/category/$slug'
    | '/movie/$slug'
    | '/shorts/$slug'
    | '/success/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/thank-you'
    | '/admin/import'
    | '/category/$slug'
    | '/movie/$slug'
    | '/shorts/$slug'
    | '/success/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$slug'
    | '/login'
    | '/thank-you'
    | '/admin/import'
    | '/category/$slug'
    | '/movie/$slug'
    | '/shorts/$slug'
    | '/success/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  LoginRoute: typeof LoginRoute
  ThankYouRoute: typeof ThankYouRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MovieSlugRoute: typeof MovieSlugRoute
  ShortsSlugRoute: typeof ShortsSlugRoute
  SuccessSlugRoute: typeof SuccessSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/success/$slug': {
      id: '/success/$slug'
      path: '/success/$slug'
      fullPath: '/success/$slug'
      preLoaderRoute: typeof SuccessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/$slug': {
      id: '/shorts/$slug'
      path: '/shorts/$slug'
      fullPath: '/shorts/$slug'
      preLoaderRoute: typeof ShortsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  LoginRoute: LoginRoute,
  ThankYouRoute: ThankYouRoute,
  CategorySlugRoute: CategorySlugRoute,
  MovieSlugRoute: MovieSlugRoute,
  ShortsSlugRoute: ShortsSlugRoute,
  SuccessSlugRoute: SuccessSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
