/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuccessSlugRouteImport } from './routes/success.$slug'
import { Route as ShortsSlugRouteImport } from './routes/shorts.$slug'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRedirectsRouteImport } from './routes/admin/redirects'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminPostsIdRouteImport } from './routes/admin/posts/$id'
import { Route as AdminPagesIdRouteImport } from './routes/admin/pages/$id'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SuccessSlugRoute = SuccessSlugRouteImport.update({
  id: '/success/$slug',
  path: '/success/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsSlugRoute = ShortsSlugRouteImport.update({
  id: '/shorts/$slug',
  path: '/shorts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesIdRoute = AdminPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/category/$slug': typeof CategorySlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/shorts/$slug': typeof ShortsSlugRoute
  '/success/$slug': typeof SuccessSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/category/$slug': typeof CategorySlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/shorts/$slug': typeof ShortsSlugRoute
  '/success/$slug': typeof SuccessSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/category/$slug': typeof CategorySlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/shorts/$slug': typeof ShortsSlugRoute
  '/success/$slug': typeof SuccessSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$slug'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/thank-you'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/redirects'
    | '/admin/users'
    | '/admin/webhooks'
    | '/category/$slug'
    | '/movie/$slug'
    | '/shorts/$slug'
    | '/success/$slug'
    | '/admin/'
    | '/admin/pages/$id'
    | '/admin/posts/$id'
    | '/admin/pages/'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/thank-you'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/redirects'
    | '/admin/users'
    | '/admin/webhooks'
    | '/category/$slug'
    | '/movie/$slug'
    | '/shorts/$slug'
    | '/success/$slug'
    | '/admin'
    | '/admin/pages/$id'
    | '/admin/posts/$id'
    | '/admin/pages'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$slug'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/thank-you'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/redirects'
    | '/admin/users'
    | '/admin/webhooks'
    | '/category/$slug'
    | '/movie/$slug'
    | '/shorts/$slug'
    | '/success/$slug'
    | '/admin/'
    | '/admin/pages/$id'
    | '/admin/posts/$id'
    | '/admin/pages/'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MovieSlugRoute: typeof MovieSlugRoute
  ShortsSlugRoute: typeof ShortsSlugRoute
  SuccessSlugRoute: typeof SuccessSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/success/$slug': {
      id: '/success/$slug'
      path: '/success/$slug'
      fullPath: '/success/$slug'
      preLoaderRoute: typeof SuccessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/$slug': {
      id: '/shorts/$slug'
      path: '/shorts/$slug'
      fullPath: '/shorts/$slug'
      preLoaderRoute: typeof ShortsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/$id': {
      id: '/admin/pages/$id'
      path: '/pages/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminPagesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPagesIdRoute: typeof AdminPagesIdRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPagesIdRoute: AdminPagesIdRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
  CategorySlugRoute: CategorySlugRoute,
  MovieSlugRoute: MovieSlugRoute,
  ShortsSlugRoute: ShortsSlugRoute,
  SuccessSlugRoute: SuccessSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
